racker/salus-telemetry-resource-management

- .gitignore
- README.md
- pom.xml
- src/main/java/com/rackspace/salus/resource_management/TelemetryResourceManagementApplication.java
- src/main/java/com/rackspace/salus/resource_management/config/AsyncConfig.java
- src/main/java/com/rackspace/salus/resource_management/config/ResourceManagementProperties.java
- src/main/java/com/rackspace/salus/resource_management/services/KafkaEgress.java
- src/main/java/com/rackspace/salus/resource_management/services/KafkaIngress.java
- src/main/java/com/rackspace/salus/resource_management/services/ResourceManagement.java
- src/main/java/com/rackspace/salus/resource_management/web/controller/ResourceApi.java
- src/main/java/com/rackspace/salus/resource_management/web/error/RestExceptionHandler.java
- src/main/java/com/rackspace/salus/resource_management/web/event/PaginatedResultsRetrievedEvent.java
- src/main/java/com/rackspace/salus/resource_management/web/event/ResourceCreatedEvent.java
- src/main/java/com/rackspace/salus/resource_management/web/event/SingleResourceRetrievedEvent.java
- src/main/java/com/rackspace/salus/resource_management/web/listener/PaginatedResultsRetrievedDiscoverabilityListener.java
- src/main/java/com/rackspace/salus/resource_management/web/listener/ResourceCreatedDiscoverabilityListener.java
- src/main/java/com/rackspace/salus/resource_management/web/listener/SingleResourceRetrievedDiscoverabilityListener.java
- src/main/java/com/rackspace/salus/resource_management/web/model/ResourceCreate.java
- src/main/java/com/rackspace/salus/resource_management/web/model/ResourceUpdate.java
- src/main/java/com/rackspace/salus/resource_management/web/model/lombok.config
- src/main/java/com/rackspace/salus/resource_management/web/util/LinkUtil.java
- src/main/resources/application-dev.yml
- src/main/resources/application.yml
- src/main/resources/data-mysql.sql
- src/test/java/com/rackspace/salus/resource_management/ResourceManagementTest.java
https://jira.rax.io/browse/SALUS-121 - Create Resource Management Service
https://jira.rax.io/browse/SALUS-137 - Resource Management HTTP Interface
https://jira.rax.io/browse/SALUS-138 - Namespace envoy labels
The initial implementation of the Resource Management service.
Adds a REST API service as well as the intermediate service to perform SQL operations.
The API performs CRUD operations for Resource objects.  It has also been configured with custom pagination/error handling to allow for easier integration with Intelligence.
For these requests, the resource management service posts new messages to the resources topic in Kafka for consumption by the Monitoring Management and Presence Monitoring services.  Additionally it consumes new attach events from Kafka to register those resources …
> Add Resource Manangement Service

- pom.xml
Discovered while looking up MySQL version needed for \SALUS-93
Updates the pom's parent to match our other apps.
Use the salus-app-base as the parent since that standardizes the Spring Boot version used, etc.
> Parent the pom to the salus-app-base

- pom.xml
- src/main/resources/application-dev.yml
- src/main/resources/application.yml
Part of SALUS-188
Fixing up a convention I had incorrectly started with setting the `server.port` in the main application.yml. Instead we should only override the default 8080 with the `dev` profile activated. Using 8080 keeps the deployment specs consistent.
> Re-configure default server port only for dev Spring profile

- pom.xml
- src/main/java/com/rackspace/salus/resource_management/services/KafkaIngress.java
- src/main/java/com/rackspace/salus/resource_management/services/ResourceManagement.java
- src/main/java/com/rackspace/salus/resource_management/web/controller/ResourceApi.java
- src/main/resources/application-dev.yml
- src/test/java/com/rackspace/salus/resource_management/ResourceManagementTest.java
For end to end integration https://jira.rax.io/browse/SALUS-205
To keep things simple for now and focused on retrieving the resource IDs associated with attached Envoys, I added a query method and REST call focused on returning just the resource IDs given specifically Envoy advertised labels.
Added a unit test to simulate an Envoy attach and then querying for its associated resource ID.
I'll also push out a PR for the corresponding monitor management changes.
> Add query to get resourceIds for given Envoy labels

- src/main/java/com/rackspace/salus/resource_management/services/ResourceManagement.java
- src/test/java/com/rackspace/salus/resource_management/ResourceManagementTest.java
Part of https://jira.rax.io/browse/SALUS-265
As of https://github.com/racker/salus-telemetry-envoy/pull/34 the Envoy is doing its own namespacing of the labels it discovers, so that no longer needs to be done in the resource manager. It does, however, still need to enforce that a resource update operation does not include user labels that conflict with the system namespaces.
Unit test updated
> Envoy now does namespacing of Envoy discovered labels

- cloudbuild-deploy.yaml
- cloudbuild.yaml
- src/main/java/com/rackspace/salus/resource_management/TelemetryResourceManagementApplication.java
- src/main/java/com/rackspace/salus/resource_management/repositories/ResourceRepository.java
- src/main/java/com/rackspace/salus/resource_management/services/ResourceManagement.java
- src/main/java/com/rackspace/salus/resource_management/web/controller/ResourceApi.java
- src/main/java/com/rackspace/salus/resource_management/web/model/ResourceCreate.java
- src/main/java/com/rackspace/salus/resource_management/web/model/ResourceUpdate.java
- src/main/resources/application-dev.yml
- src/test/java/com/rackspace/salus/resource_management/ResourceApiTest.java
- src/test/java/com/rackspace/salus/resource_management/ResourceManagementTest.java
Part of https://jira.rax.io/browse/SALUS-305
We had previously identified that `getResourceIdsWithEnvoyLabels` was an awkward method to maintain since it mostly duplicated the other labels query. Since I was already making changes in monitor management, I went ahead and shifted the usage of this "get IDs" variant over to the main "get resources" query.
During testing I also found that `updateEnvoyLabels` wasn't properly handling the case when new envoy labels were added during an update. That also led me to find it needed to leverage the label namespacing to differentiate labels provided via the resource API from those provided during envoy attach.
Unit tests were updated
> Fix updateEnvoyLabels and remove getResourceIdsWithEnvoyLabels

- pom.xml
Now that salus-telemetry-protocol has a released version we need to start shifting references to that rather than snapshot.
> Pin salus-telemetry-protocol to 0.1.1

- README.md
- pom.xml
- src/main/java/com/rackspace/salus/resource_management/web/client/ResourceApi.java
- src/main/java/com/rackspace/salus/resource_management/web/client/ResourceApiClient.java
- src/main/java/com/rackspace/salus/resource_management/web/controller/ResourceApiController.java
- src/test/java/com/rackspace/salus/resource_management/ResourceApiTest.java
- src/test/java/com/rackspace/salus/resource_management/web/client/ResourceApiClientTest.java
- src/test/java/com/rackspace/salus/resource_management/web/controller/ResourceApiControllerTest.java
Part of https://jira.rax.io/browse/SALUS-311
Adds an internal REST API client similar to the [MonitorApiClient](https://github.com/racker/salus-telemetry-monitor-management/blob/master/src/main/java/com/rackspace/salus/monitor_management/web/client/MonitorApiClient.java)
So far includes the query method needed by the monitor management when processing a resource event.
New unit tests have been added.
> Add ResourceApiClient

- src/main/java/com/rackspace/salus/resource_management/services/KafkaEgress.java
- src/main/java/com/rackspace/salus/resource_management/services/ResourceManagement.java
- src/test/java/com/rackspace/salus/resource_management/ResourceManagementTest.java
https://jira.rax.io/browse/SALUS-293
depends on: https://github.com/racker/salus-telemetry-model/pull/40
removes the setting of the extra fields that are no longer used by the resource event, when resourceMan creates it.
unit tests
> update resource manager for new resource event

- src/main/java/com/rackspace/salus/resource_management/repositories/ResourceRepository.java
- src/main/java/com/rackspace/salus/resource_management/services/ResourceManagement.java
- src/main/java/com/rackspace/salus/resource_management/web/client/ResourceApi.java
- src/main/java/com/rackspace/salus/resource_management/web/client/ResourceApiClient.java
- src/main/java/com/rackspace/salus/resource_management/web/controller/ResourceApiController.java
- src/test/java/com/rackspace/salus/resource_management/web/client/ResourceApiClientTest.java
Adds a new endpoint to the resource api client.
I added it to the interface and then implemented a version of it in both the controller and the client.  It is unlikely the new controller method will be used, as the clients will want to get a streaming result vs. a large bulk payload, however, it had to be implemented since it is defined in the interface.
Implemented a likely unnecessary method seemed like the best option.  The alternatives are defining a default method in the interface that does nothing or moving away from using the interface. 
Run tests.
Presence monitoring now utilizes this api client, and a method for this endpoint was required.
> Add getExpectedEnvoys to API interface

- src/main/java/com/rackspace/salus/resource_management/repositories/ResourceRepository.java
- src/main/java/com/rackspace/salus/resource_management/services/ResourceManagement.java
- src/main/java/com/rackspace/salus/resource_management/web/controller/ResourceApiController.java
- src/test/java/com/rackspace/salus/resource_management/ResourceApiTest.java
- src/test/java/com/rackspace/salus/resource_management/ResourceManagementTest.java
- src/test/java/com/rackspace/salus/resource_management/web/controller/ResourceApiControllerTest.java
Removes all the `CriteriaBuilder` logic for building sql queries and replaces it by using standard repository options.
The "how" is fairly obvious.  The only real decision was to start using `Optional` fields where we are getting at most one returned object.  I like this overall, but the downside is it makes the tests a little more tedious due to having to do various `isPresent()` and `get()` calls.
Run all tests.  They still work!
Cleans up the code and standardizes things across all repos.
Incoming PRs for monitor management and model repo... I think that'll be it.
> Remove CriteriaBuilder and use repository methods instead

- src/main/java/com/rackspace/salus/resource_management/services/ResourceManagement.java
Due to removing the CriteriaBuilder logic, these fields are no longer needed.
> Remove unused things

- src/test/java/com/rackspace/salus/resource_management/ResourceManagementTest.java
Due to https://github.com/racker/salus-telemetry-model/pull/46 the label namespace delimiter is now an underscore. The unit test was failing since a prefix of "system." was circumventing the validation that disallows "system_".
> Updating unit test for use of underscore label delimiter

- src/test/java/com/rackspace/salus/resource_management/ResourceManagementTest.java
With this PR https://github.com/racker/salus-telemetry-model/pull/46 the resource labels are now subject to the validation of label keys.
The unit tests here needed to be updated to use valid labels without dots.
> Correct the resource labels used in unit test to pass validator

- .github/PULL_REQUEST_TEMPLATE.md
- src/main/java/com/rackspace/salus/resource_management/services/KafkaEgress.java
- src/main/java/com/rackspace/salus/resource_management/services/ResourceManagement.java
- src/test/java/com/rackspace/salus/resource_management/ResourceManagementTest.java
- src/test/java/com/rackspace/salus/resource_management/services/KafkaEgressTest.java
https://jira.rax.io/browse/SALUS-360
Extends the processing of Envoy attachment events by producing a new `ReattachedEnvoyResourceEvent` event introduced by https://github.com/racker/salus-telemetry-model/pull/52 when the resource already existed. That event will be produced in addition to the resource change event, if there was a change in the resource.
Design background is provided in https://github.com/racker/salus-telemetry-bundle/pull/50
Unit tests updated and added.
> ReattachedEnvoyResourceEvent when Envoy attaches to existing resource

- src/main/java/com/rackspace/salus/resource_management/services/ResourceManagement.java
- src/main/java/com/rackspace/salus/resource_management/web/controller/ResourceApiController.java
- src/test/java/com/rackspace/salus/resource_management/ResourceManagementTest.java
- src/test/java/com/rackspace/salus/resource_management/web/controller/ResourceApiControllerTest.java
Basically the same as https://github.com/racker/salus-telemetry-monitor-management/pull/47
Updates the monitor and zone apis so that pagination params can be specified in the request and handled correctly.
Also fixes the indentation of some files... seeing how github is interpreting them, I now wish I didn't click that button during these changes.  It makes this PR more painful to review than it should have been.
Reviewing the test changes might be the easiest way to see the differences.
* Mostly this was just converting the use of Lists over to Pages
* The ApiController no longer implements to API interface.
* Fixed some urls - e.g. prepend with `/admin`
* Updated responses to be `PagedContent`
* I did remove some methods that weren't used.
* `getExpectedEnvoys` etc. I think these were …
> Fix API Pagination

- src/main/java/com/rackspace/salus/resource_management/entities/Resource.java
It dawned on me that the resource labels table created by JPA/Hibernate may not have indexes declared on it by default and indeed that was the case. With the annotation change in this PR I now see the index being created:
```
Hibernate: create index IDXsfyp9clv4p78phb65j12dp8av on resource_labels (id, labels_key, labels)
```
Existing unit tests. Ideally we would have some kind of benchmarking/stress test setup where could have seen a before and after performance improvement.
> Declare JPA indexing of resource labels table

- pom.xml
While using this pom for a new module I noticed the `salus-test` dependency needed to be limited to test scope.
> Limit salus-test maven dependency to test scope

- src/main/java/com/rackspace/salus/resource_management/web/client/ResourceApiClient.java
- src/main/java/com/rackspace/salus/resource_management/web/controller/ResourceApiController.java
- src/test/java/com/rackspace/salus/resource_management/web/client/ResourceApiClientTest.java
- src/test/java/com/rackspace/salus/resource_management/web/controller/ResourceApiControllerTest.java
This was already changed in the public API.  Changing within the API client here means nothing else is needed (except insomnia).
> Make url kebab-case

- pom.xml
https://jira.rax.io/browse/SALUS-474
The upgrade of jetcd to 0.3.0 in common and etcd-adapter causes the following Maven dependency resolution issue:
```
[ERROR] Failed to execute goal on project salus-telemetry-resource-management: Could not resolve dependencies for project com.rackspace.salus:salus-telemetry-resource-management:jar:0.0.1-SNAPSHOT: Failed to collect dependencies for com.rackspace.salus:salus-telemetry-resource-management:jar:0.0.1-SNAPSHOT: Could not resolve version conflict among [com.rackspace.salus:salus-telemetry-protocol:jar:0.2-SNAPSHOT -> io.grpc:grpc-netty:jar:1.15.0 -> io.grpc:grpc-core:jar:[1.15.0,1.15.0], com.rackspace.salus:salus-telemetry-protocol:jar:0.2-SNAPSHOT -> io.grpc:grpc-protobuf:jar:1.15.0 -> io.grpc:grpc-core:jar:1.15.0, …
```
> Upgrade salus-telemetry-protocol to align grpc with jetcd 0.3.0

- src/main/java/com/rackspace/salus/resource_management/entities/Resource.java
- src/main/java/com/rackspace/salus/resource_management/repositories/ResourceRepository.java
- src/main/java/com/rackspace/salus/resource_management/services/ResourceManagement.java
- src/main/java/com/rackspace/salus/resource_management/web/client/ResourceApi.java
- src/main/java/com/rackspace/salus/resource_management/web/client/ResourceApiClient.java
- src/main/java/com/rackspace/salus/resource_management/web/controller/ResourceApiController.java
- src/test/java/com/rackspace/salus/resource_management/ResourceManagementTest.java
- src/test/java/com/rackspace/salus/resource_management/web/client/ResourceApiClientTest.java
- src/test/java/com/rackspace/salus/resource_management/web/controller/ResourceApiControllerTest.java
Returns all distinct tenant ids that the resource management service is aware of.
Simple db query + adds api endpoints + tests.
Run tests!
Policy Management will query this when a policy change occurs and then send out a single `PolicyEvent` for each tenant.  This is so the monitor management service (and other in future) will be able to consume these one at a time, deciding what action needs to happen for an individual tenant, rather than being overloaded by trying to handle all tenants at once.
> Add endpoint to get all tenants with at least one resource

- cloudbuild.yaml
- src/main/java/com/rackspace/salus/resource_management/web/controller/RestExceptionHandler.java
I noticed monitor-management builds were failing sometimes on symbol mismatches from resource-management changes that were still in active PR branches. For example
https://console.cloud.google.com/cloud-build/builds/be12c37d-fc01-4971-b7f1-c45dd44feb15?project=salus-220516&authuser=1&organizationId=767495606862
Fixed the non-deploy build config to match our others.
Do a non-master/tag GCP build.
> The non-deploy build config should just use the verify goal

- src/main/java/com/rackspace/salus/resource_management/services/ResourceManagement.java
- src/main/java/com/rackspace/salus/resource_management/web/client/ResourceApi.java
- src/main/java/com/rackspace/salus/resource_management/web/client/ResourceApiClient.java
- src/main/java/com/rackspace/salus/resource_management/web/controller/ResourceApiController.java
- src/main/resources/sql-queries/resource_label_matching_OR_query.sql
- src/main/resources/sql-queries/resource_label_matching_query.sql
- src/test/java/com/rackspace/salus/resource_management/ResourceManagementTest.java
- src/test/java/com/rackspace/salus/resource_management/web/client/ResourceApiClientTest.java
- src/test/java/com/rackspace/salus/resource_management/web/controller/ResourceApiControllerTest.java
https://jira.rax.io/browse/SALUS-606
Support logical OR as well as logical AND processing for matching labels. The label matching in here is from monitors to resources so we dont need to combine the results together since the monitor will tell us what sort of processing we need to do. 
I duplicated the AND query and modified it for handling OR processing. 
Run the unit tests. The functions that are testing this end in "UsingOr"
We considered handling this in a hybrid approach through JPA or Hibernate. Neither of those places seemed to have a good way of querying map values. 
There was also a consideration for doing this through a hybrid approach but that would still require the writing of the OR based query and then handling the rest of the processing server side. Since we already have …
> Logical OR processing for resources

- src/main/java/com/rackspace/salus/resource_management/web/client/ResourceApi.java
- src/main/java/com/rackspace/salus/resource_management/web/client/ResourceApiClient.java
Adds a create endpoint to the api client.
I included `MultiValueMap<String, String> headers` so that this can be used against the public api and provide an `x-auth-token`.  I spoke to @itzg briefly about that before and if the need arises we might want to add that to all the api client methods (or at least any we add from here on) so that it is more of a comprehensive client that can be used for multiple purposes and not just internal service-to-service requests.
I'm utilizing this client in the migration app.
> Add create endpoint to api client

- src/main/java/com/rackspace/salus/resource_management/config/DatabaseConfig.java
- src/main/resources/application-dev.yml
https://jira.rax.io/browse/SALUS-684
Uses flyway for schema management by switching over to the `@EnableSalusJpa` config annotation and removing explicit setting of hibernate auto ddl.
Existing unit tests
- https://github.com/racker/salus-telemetry-model/pull/85
> Use flyway for schema management

- src/main/java/com/rackspace/salus/resource_management/web/controller/RestExceptionHandler.java
When creating a duplicate monitor translation operator, the REST API would respond with a 503 (service unavailable) and the message contained no indication of the constraint violation.
Turns out all JDBC exceptions are getting lumped into the 503, so I added a conditional to check for the constraint violation and propagate the message from it along with a 400 response. It looks like a 409 might be a possible status code, so I'll open that choice up for a vote.
Can't really test this one since even integration-unit tests don't seem to make use of the error handler.
> Improved HTTP status returned for JDBC data integrity violations

- pom.xml
- src/main/resources/application-dev.yml
- src/test/java/com/rackspace/salus/resource_management/ResourceManagementTest.java
Part of https://jira.rax.io/browse/SALUS-738
The Spring Boot upgrade from 2.1.8 to 2.2.4 included an upgrade of h2 from 1.4.199 to 1.4.200. Even though that version of h2 brings some nice features like json data type support, it also became more picky (correctly so) about the SQL used in the flyway migration files.
With the Spring Boot 2.2.4 upgrade the default must have changed for `spring.kafka.listener.missing-topics-fatal` from false to true or it's a new condition spring kafka checks. In any case, when starting one of our kafka-consuming apps locally it was failing to start since I had a fresh kafka container without the topic it wanted. It's a good property and default to have in production, but annoying locally.
Use the new `@EnableTestContainersDatabase` annotation provided by …
> Updated unit test to use mysql testcontainers

- src/main/resources/sql-queries/resource_label_matching_OR_query.sql
- src/main/resources/sql-queries/resource_label_matching_query.sql
- src/test/java/com/rackspace/salus/resource_management/ResourceManagementTest.java
https://jira.rax.io/browse/SALUS-737
Make sure that a resource with no labels will still match everything
Alters the query to make sure that we are using an OUTER JOIN to find the resources that dont have any labels attached to them and still makes sure that we are only grabbing the resources for that tenant.
Run the ResourceMangementTest's
It needs to be done at query time. We can't do it on the server because by the time we get there we would have already filtered out the resources that don't have labels.
Everything should be done
> Fixed resource management label query and added extra tests

- pom.xml
Github notified us of a security alert
https://github.com/racker/salus-telemetry-resource-management/network/alert/pom.xml/org.codehaus.jackson:jackson-mapper-asl/closed
We had a direct dependency on that library added by https://github.com/racker/salus-telemetry-resource-management/pull/20 that apparently wasn't even needed. All modern jackson libraries are situated in the fasterxml org and are supplied transitively by Spring dependencies.
Removed the dependency and everything still builds fine.
All the tests still work.
> Removed codehaus jackson-mapper-asl dependency

- src/main/java/com/rackspace/salus/resource_management/services/ResourceManagement.java
- src/test/java/com/rackspace/salus/resource_management/ResourceManagementTest.java
https://jira.rax.io/browse/SALUS-805
When resources were present with no metadata, the `resource-metadata-keys` API endpoint would respond with a 500 and logs showed
```
java.lang.NullPointerException: null
--
at com.rackspace.salus.resource_management.services.ResourceManagement.lambda$getTenantResourceMetadataKeys$6(ResourceManagement.java:480)
at com.rackspace.salus.resource_management.services.ResourceManagement.getTenantResourceMetadataKeys(ResourceManagement.java:484)
at com.rackspace.salus.resource_management.web.controller.ResourceApiController.getResourceMetadataKeys(ResourceApiController.java:205)
```
Filter away the null metadata maps.
Added a unit test to recreate the bug and verify the fix.
cc @FarajiA
> Fixed get-metadata-keys to handle resources with null metadata

- src/main/java/com/rackspace/salus/resource_management/web/model/ResourceDTO.java
This change goes along with my other zone policy changes:
https://github.com/racker/salus-telemetry-monitor-management/pull/164
https://github.com/racker/salus-policy-management/pull/31
By ensuring an empty map is set instead of `null` it allows for cleaner tests in the other repos that mock out `ResourceDTO`s
> Default to empty maps

- pom.xml
- src/main/java/com/rackspace/salus/resource_management/TelemetryResourceManagementApplication.java
- src/test/java/com/rackspace/salus/resource_management/web/client/ResourceApiClientTest.java
- src/test/java/com/rackspace/salus/resource_management/web/controller/ResourceApiControllerTest.java
See https://github.com/racker/salus-telemetry-model/pull/124
Utilizes the `@EnableTenantVerification` annotations and adds some simple tests to show it took effect.
> Enable tenant id verification

- pom.xml
Part of https://jira.rax.io/browse/SALUS-852
Aligning versions on latest salus-telemetry-protocol to pick up https://github.com/racker/salus-telemetry-protocol/pull/21 and then re-snapshot-ed at https://github.com/racker/salus-telemetry-protocol/commit/53589514f9d44b90661c097fead38c31232449d6
> Upgraded salus-telemetry-protocol for grpc 1.28.1

- src/main/java/com/rackspace/salus/resource_management/services/ResourceManagement.java
- src/test/java/com/rackspace/salus/resource_management/ResourceManagementTest.java
Store empty resource metadata as an empty map instead of null.
Resources can be created in two places, via an api request or via an envoy attach.  Ensure each of those set an empty map if null is seen.
Locally and the newly updated tests.
`NullPointerException` was being thrown when we try to get the `region` of a resource.
Since `metadata` is stored as `json` instead of an element collection, it would get stored/retrieved as null instead of an empty list (like what would happen with labels).
> Ensure metadata is not stored as null

- src/main/java/com/rackspace/salus/resource_management/web/model/ResourceCreate.java
- src/test/java/com/rackspace/salus/resource_management/web/controller/ResourceApiControllerTest.java
Following on from https://github.com/racker/salus-telemetry-resource-management/pull/71 this allows for dots/periods to be used in resource IDs. The existing validation became to restrictive for our own monitoring where we are using FQDNs for the resource ID.
Unit tests update
> Updated resource ID validation to allow dots for FQDNs

- src/main/java/com/rackspace/salus/resource_management/web/client/ResourceApi.java
- src/main/java/com/rackspace/salus/resource_management/web/client/ResourceApiClient.java
- src/test/java/com/rackspace/salus/resource_management/web/client/ResourceApiClientTest.java
https://jira.rax.io/browse/SALUS-1014
Removed getByResourceId from ResourceApiClient
This can be tested by unit test cases
No need for get resource id method as it can be used as DB retrieval call
> Removed getByResourceId from ResourceApiClient
